name: udisks
version: 0.0.0-dev.2

description:
  Provides a client to connect to UDisks - the service that accesses and manipulates disks, storage devices and technologies on Linux.

homepage: https://github.com/canonical/udisks.dart

environment:
  sdk: '>=2.7.2 <3.0.0'

dependencies:
  dbus: ^0.0.0-dev.20

dev_dependencies:
  pedantic: ^1.9.0
